[pytest]
python_files = pytest_*.py test_*.py

# Several examples share the same test file basename so import by file path 
# instead of by module name to avoid collisions.
addopts = --import-mode=importlib

# Make `tests/` directory importable from any *.py file
pythonpath = tests
