message(STATUS "z88dk z80asm assembler detected.")

set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm)
set(CMAKE_ASM_OUTPUT_EXTENSION ".o")

set(CMAKE_DEPFILE_FLAGS_ASM "")
set(CMAKE_ASM_DEPFILE_STYLE NONE)

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o<OBJECT> <SOURCE>")

# The way the final binary (C or ASM) is linked highly depends on the assembler.
set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_LINKER> <LINK_FLAGS> <LINK_LIBRARIES> <TARGET> ${SDCC_REL0} <OBJECTS>")

    set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_ASM_COMPILER> <LINK_FLAGS> <LINK_LIBRARIES> -b -o<TARGET> <OBJECTS>")

set(CMAKE_EXECUTABLE_SUFFIX ".bin")
