## Zeal 8-bit CI (emulator, UART output)

CONFIG_CPU_FREQ=10000000
CONFIG_TARGET="zeal8bit"
CONFIG_TARGET_ZEAL_8_BIT=y
# CONFIG_TARGET_TRS_80 is not set
# CONFIG_TARGET_AGON_LIGHT is not set

#
# Zeal 8-bit Computer configuration
#
CONFIG_TARGET_NUMBER=1
CONFIG_TARGET_HAS_MMU=y
CONFIG_TARGET_HAS_DRIVERS_HOOK=y
CONFIG_KERNEL_RAM_PHYS_ADDRESS=0x88000
CONFIG_KERNEL_TARGET_HAS_MMU=y
CONFIG_TARGET_ENABLE_TFCARD=y
CONFIG_TARGET_ENABLE_COMPACTFLASH=y

#
# CompactFlash driver configuration
#
CONFIG_TARGET_COMPACTFLASH_ADDRESS=0x70
CONFIG_TARGET_COMPACTFLASH_TIMEOUT=500
# end of CompactFlash driver configuration

CONFIG_ENABLE_EMULATION_HOSTFS=y
CONFIG_TARGET_ENABLE_VIDEO=y
# CONFIG_TARGET_STDOUT_VIDEO is not set
CONFIG_TARGET_STDOUT_UART=y
CONFIG_TARGET_KEYBOARD_PS2=y
# CONFIG_TARGET_KEYBOARD_PARL is not set
CONFIG_TARGET_KEYBOARD_QWERTY=y
# CONFIG_TARGET_KEYBOARD_AZERTY is not set
# CONFIG_TARGET_KEYBOARD_DVORAK is not set
# CONFIG_TARGET_KEYBOARD_COLEMAK is not set
CONFIG_TARGET_ENABLE_PS2_EXTENSION_BOARD=y

#
# PS/2 extension board configuration
#
CONFIG_PS2_EXT_IO_ADDR=0x20
CONFIG_PS2_EXT_KEYBOARD_PORT0=y
CONFIG_PS2_EXT_MOUSE_PORT1=y
# end of PS/2 extension board configuration

CONFIG_TARGET_ENABLE_MOUSE=y
# CONFIG_TARGET_MOUSE_SNES is not set
CONFIG_TARGET_MOUSE_PS2=y
# CONFIG_TARGET_UART_SET_MONITOR_SIZE is not set
# end of Zeal 8-bit Computer configuration

#
# Kernel configuration
#
CONFIG_KERNEL_REPRODUCIBLE_BUILD=y
CONFIG_KERNEL_STACK_ADDR=0xFFFF
CONFIG_KERNEL_RAM_START=0xC000
# CONFIG_KERNEL_COLDBOOT_HOOK is not set
# CONFIG_KERNEL_EXIT_HOOK is not set
CONFIG_KERNEL_DRIVERS_HOOK=y
CONFIG_KERNEL_MAX_NESTED_PROGRAMS=3
CONFIG_KERNEL_STALL_ON_INIT_EXIT=y
CONFIG_KERNEL_MAX_LOADED_DRIVERS=16
CONFIG_KERNEL_MAX_OPENED_DEVICES=16
CONFIG_KERNEL_MAX_OPENED_FILES=16
CONFIG_KERNEL_PATH_MAX=128
CONFIG_KERNEL_INIT_EXECUTABLE="a:/init.bin"
CONFIG_KERNEL_INIT_EXECUTABLE_ADDR=0x4000
CONFIG_KERNEL_LOG_BOOT_MOUNTED_DISKS=y
CONFIG_KERNEL_ENABLE_ZEALFS_SUPPORT=y
# CONFIG_KERNEL_ZEALFS_V1 is not set
CONFIG_KERNEL_ZEALFS_V2=y
CONFIG_KERNEL_ENABLE_MBR_SUPPORT=y
# end of Kernel configuration

CONFIG_ENABLE_ROMDISK=y

#
# Romdisk configuration
#
CONFIG_ROMDISK_OFFSET_PAGES=1
CONFIG_ROMDISK_EXTRA_FILES=""
CONFIG_ROMDISK_INCLUDE_INIT_BIN=y
# CONFIG_INITBIN_ENABLE_COREUTILS is not set
CONFIG_ROMDISK_IGNORE_HIDDEN=y
# end of Romdisk configuration
