set(CMAKE_SYSTEM_NAME Generic CACHE INTERNAL "")

# Disable C/C++ compilers
set(CMAKE_C_COMPILER "" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER "" CACHE INTERNAL "")
set(CMAKE_C_COMPILER_WORKS TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE INTERNAL "")

# ASM compiler settings - all cached!
set(CMAKE_ASM_COMPILER z88dk-z80asm)
set(CMAKE_ASM_COMPILER_ID Z88DK)
set(CMAKE_ASM_COMPILER_WORKS TRUE)
set(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm)
set(CMAKE_EXECUTABLE_SUFFIX ".bin")

# Disable dependency generation
set(CMAKE_DEPENDS_USE_COMPILER FALSE)
set(CMAKE_DEPFILE_FLAGS_ASM "")
set(CMAKE_ASM_DEPFILE_STYLE NONE)

# Compilation and linking commands
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o<OBJECT> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_ASM_COMPILER> -b -o<TARGET> <OBJECTS>")
