name: Build All Platforms

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-zos:
    name: Build Zeal 8-bit OS
    uses: ./.github/workflows/build-zos.yml

    strategy:
      matrix:
        include:
          - target: zeal8bit
            artifact-name: zos_target_zeal8bit_hw
          - target: zeal8bit/emu
            artifact-name: zos_target_zeal8bit_emulator
          - target: zeal8bit/uart
            artifact-name: zos_target_zeal8bit_hw_uart
          - target: agon
            artifact-name: zos_target_agon
            skip-romdisk: true
          - target: trs80
            artifact-name: zos_target_trs80
            skip-romdisk: true
    with:
      target: ${{ matrix.target }}
      artifact-name: ${{ matrix.artifact-name }}
      romdisk: ${{ !matrix['skip-romdisk'] }}

  create-release:
    name: Create Draft Release
    needs: [build-zos]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./artifacts

      - name: Create Release Archives
        run: |
          cd artifacts
          for dir in */; do
            # Remove trailing slash
            name="${dir%/}"
            echo "Packaging $name..."
            # Create a zip with the same name as the folder
            (cd "$name" && zip -r "../${name}.zip" .)
          done
          cd ..

      - name: Generate Release Info
        id: tag
        run: |
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "release_date=$(date -u +"%Y-%m-%d %H:%M UTC")" >> $GITHUB_OUTPUT

      - name: Delete Existing Draft Releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd ${{ github.workspace }}/
          gh release delete "latest"  --repo ${{ github.repository }} --yes || true

      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
          name: Latest build (${{ steps.tag.outputs.sha }})
          body: |
            Built from commit: ${{ steps.tag.outputs.sha }}
            Branch: ${{ github.ref_name }}
            Date: ${{ steps.tag.outputs.release_date }}
          tag_name: latest
          preserve_order: true
          files: |
            artifacts/zos_target_zeal8bit_hw.zip
            artifacts/zos_target_zeal8bit_emulator.zip
            artifacts/zos_target_zeal8bit_hw_uart.zip
            artifacts/zos_target_agon.zip
            artifacts/zos_target_trs80.zip
